<?php
if (!defined('ABSPATH'))
{
    exit();
}

if (function_exists('acf_add_local_field_group')):

    acf_add_local_field_group(array(
        'key' => 'group_623e7d47f0f07',
        'title' => 'Dados do Lojista',
        'fields' => array(
            array(
                'key' => 'field_623e800ff83a5',
                'label' => 'Endereço da Loja',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'placement' => 'top',
                'endpoint' => 0,
            ) ,
            array(
                'key' => 'field_623e7de4f0c75',
                'label' => 'CEP',
                'name' => 'shopkeeper_zip_code',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e7d8af0c73',
                'label' => 'Endereço',
                'name' => 'shopkeeper_address',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e7e0af0c76',
                'label' => 'Número',
                'name' => 'shopkeeper_number_address',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e7dc3f0c74',
                'label' => 'Bairro',
                'name' => 'shopkeeper_neighborhood',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e7f380a6a9',
                'label' => 'Estado',
                'name' => 'shopkeeper_state',
                'type' => 'select',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'choices' => array(
                    'Acre' => 'Acre',
                    'Alagoas' => 'Alagoas',
                    'Amapá' => 'Amapá',
                    'Amazonas' => 'Amazonas',
                    'Bahia' => 'Bahia',
                    'Ceará' => 'Ceará',
                    'Distrito Federal' => 'Distrito Federal',
                    'Espírito Santo' => 'Espírito Santo',
                    'Goiás' => 'Goiás',
                    'Maranhão' => 'Maranhão',
                    'Mato Grosso' => 'Mato Grosso',
                    'Mato Grosso do Sul' => 'Mato Grosso do Sul',
                    'Minas Gerais' => 'Minas Gerais',
                    'Pará' => 'Pará',
                    'Paraíba' => 'Paraíba',
                    'Paraná' => 'Paraná',
                    'Pernambuco' => 'Pernambuco',
                    'Piauí' => 'Piauí',
                    'Rio de Janeiro' => 'Rio de Janeiro',
                    'Rio Grande do Norte' => 'Rio Grande do Norte',
                    'Rio Grande do Sul' => 'Rio Grande do Sul',
                    'Rondônia' => 'Rondônia',
                    'Roraima' => 'Roraima',
                    'Santa Catarina' => 'Santa Catarina',
                    'São Paulo' => 'São Paulo',
                    'Sergipe' => 'Sergipe',
                    'Tocantins' => 'Tocantins',
                ) ,
                'default_value' => 'São Paulo',
                'allow_null' => 0,
                'multiple' => 0,
                'ui' => 0,
                'return_format' => 'value',
                'ajax' => 0,
                'placeholder' => '',
            ) ,
            array(
                'key' => 'field_623e7e1af0c77',
                'label' => 'Cidade',
                'name' => 'shopkeeper_city',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e802ef83a6',
                'label' => 'Dados de Contato',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'placement' => 'top',
                'endpoint' => 0,
            ) ,
            array(
                'key' => 'field_623fc32b633c0',
                'label' => 'Nome Fantasia',
                'name' => 'shopkeeper_fantasy_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623fc2ed633bf',
                'label' => 'Razão Social',
                'name' => 'shopkeeper_corporate_name',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623fc3601d764',
                'label' => 'CNPJ',
                'name' => 'shopkeeper_cnpj',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e8076f83a8',
                'label' => 'Telefone',
                'name' => 'shopkeeper_phone',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e8044f83a7',
                'label' => 'Whatsapp',
                'name' => 'shopkeeper_whatsapp',
                'type' => 'text',
                'instructions' => '',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ) ,
            array(
                'key' => 'field_623e808cf83a9',
                'label' => 'Website',
                'name' => 'shopkeeper_website',
                'type' => 'url',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
            ) ,
            array(
                'key' => 'field_623e809bf83aa',
                'label' => 'E-mail',
                'name' => 'shopkeeper_email',
                'type' => 'email',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ) ,
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
            ) ,
        ) ,
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'shopkeeper',
                ) ,
                array(
                    'param' => 'current_user_role',
                    'operator' => '==',
                    'value' => 'administrator',
                ) ,
            ) ,
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'shopkeeper',
                ) ,
                array(
                    'param' => 'current_user_role',
                    'operator' => '==',
                    'value' => 'editor',
                ) ,
            ) ,
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'shopkeeper',
                ) ,
                array(
                    'param' => 'current_user_role',
                    'operator' => '==',
                    'value' => 'author',
                ) ,
            ) ,
        ) ,
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
        'show_in_rest' => 0,
    ));

endif;

